### ISSUE TITLE
Mask versus Ground Truth

### ISSUE THREAD

**Issue by muschellij2** [muschellij2/flexconn#2]
So in FLEXCONN, when they use `mask`, they mean the ground truth.  So they make patches for all the cases where a voxel is 1 (lesion).  You may want to make patches for all the voxels or balance the # of voxels with lesion and those without.  Therefore, I think we should separate the argument `mask` with `ground_truth` or `y` or something similar.

For example, the `mask` may be indicating voxels inside the brain/regions of interest, but `y` would be the mask indicating the lesion presence.  I think these are important distinctions, especially when you go for prediction, where you don't have a "ground truth" necessarily, but do have a mask where you want to get a probability for each voxel.

@skeydan

**Comment by skeydan** [comment]
I'm not sure I totally understand... I'd leave such questions to you then, - only I'm wondering, if we do the prediction exactly like they do, do we need such a distinction?

**Comment by muschellij2** [comment]
If we do it like they do, then no, I think we don't need a distinction.  I would prefer to have the ability, however, to create patches, predict, then create a volume.  

So let's say you have a new image and want to predict on it.  You need to tell it which voxels to predict, or predict over the whole mask.  In most cases, you may not have a gold standard, so the mask is the whole brain.   Thus "mask" and "outcome" are not synonymous.  Also, more importantly, when FLEXCONN trains, they do not seem to train on any non-cases (where Y = 0) as the mask you put in is the lesion mask.  I'm unsure if that matters, but seems like you'd want to balance the cases so that you don't have a lot of false positives.

**Comment by skeydan** [comment]
Thanks for explaining! For

1) when predicting, you anyway have the t1 and fl only, there is no mask, and I think they predict over the whole image at once, with the exception that they have to do it once per channel (3rd dim) because they do it in  2d.
Looking at their prediction function

```
def apply_model(image1, image2, pred_model):

    dim = image1.shape
    dim_2d = (1, dim[0], dim[1], 1)

    slice_2d_t1 = np.zeros(dim_2d, dtype=np.float16)
    slice_2d_fl = np.zeros(dim_2d, dtype=np.float16)
    output_image = np.zeros(dim, dtype=np.float16)

    for k in range(dim[2]):
        slice_2d_t1[0, :, :, 0] = image1[:, :, k]
        slice_2d_fl[0, :, :, 0] = image2[:, :, k]
        pred = pred_model.predict([slice_2d_t1, slice_2d_fl])
        output_image[:, :, k] = pred[0, :, :, 0]

    return output_image
```

what would you want to do differently?

Also I'm wondering if that isn't a terminology thing perhaps? To me as an outsider, from just working with the code, "mask" would be a synonym to ground truth.

Reg.

2) yes I had that thought while translating, but I was leaving it to the experts and also, I was thinking that that's what the blur is for (or one of the things the blur is for), because with padding and blurring the ground truth ends up with quite some zeros (as I saw by inspecting it)

**Comment by muschellij2** [comment]
So 1.  is now the default of `flexconn_predict`.  The naming of `mask` and `y`/`ground_truth` are still outstanding.  I'll think more on that.
