### ISSUE TITLE
adapt flexconn_wpackage.R for use in training 

### ISSUE THREAD

**Issue by skeydan** [muschellij2/flexconn#5]
hi John

I've switched to using the above file now. There are some things that had to be changed just to make it runnable, - can you have a look at the changes resp. inline comments?
I'm sure you'd like to adapt this further.

For example, ```get_patches``` does a lot more things than I expected, - but I'll leave all these questions to you :-)

A lot of things depend on how you think this should get used. For example, should the above file be included not as an API, but as "example usage"?
How much freedom should the user have in specifying model parameters, etc.
(Concrete example:  the call to ```compile``` could be moved to ```flexconn_model()```.

Overall I'd leave that to you because you know best how users will want to use it.
In general I think I'd keep it as what the name says: a port of the original model.
We can always do others later, right? :-)

**Comment by muschellij2** [comment]
I've adapted this a bit.  The `get_patches` does padding and normalization.  If you want only the patches back , you can set ` only_patches = TRUE`, which I did in the example now.

**Comment by skeydan** [comment]
Great! I'd even go further and do it "opposite way round" - remove the manual calls from ```flexconn_wpackage.R``` so that gets as concise as possible?

**Comment by muschellij2** [comment]
I don't understand exactly.  There are some things that can be abstracted away, such as taking a list of atlases and then making a huge patch list, but mostly I think it's as functionalized it needs to be for a package.

Also, I found that `KernSmooth::bkde` did not give the same results as FLEXCONN for estimation.  So I made `flexconn_image_peak` (https://github.com/muschellij2/flexconn/blob/master/R/normalize_image.R#L92), which is used in `normalize_image`.  This may be due to:

1.  How the percentile is calculated in numpy.  I figured out how they do it and  created `numpy_percentile` (https://github.com/muschellij2/flexconn/blob/master/R/numpy_percentile.R).  (`stats::quantile` is knowingly different)
2.  How the KDE is estimated in `statsmodels`.  It may be a bit different than `bkde` I guess.
3.  How the peaks are found using `pracma` or `scipy`

Either way - what are your thoughts on using `flexconn_image_peak` vs `image_peak`?

**Comment by skeydan** [comment]
Hi John,

great you tested this and implemented a solution! I'm really leaving this to the expert :-)
All I think is that it makes sense - as this is basically a port of the python code - to do it "their way" as closely as possible.

Thanks for fixing `flexconn_wpackage.R`! I'll commit a version soon with the updated testing code (probably opening a different issue for discussing that). Also I guess we could rename this one to ```flexconn.R``` and the remove the other one?

**Comment by muschellij2** [comment]
Moved R files over.  I've added a switch for peak estimation but defaults to Python.
